### ISSUE TITLE
RewardZone not working as expected in multi-agent scenarios

### ISSUE THREAD

**Issue by emasquil** [gaorkl/simple-playgrounds#73]
The `RewardZone` object only gives a reward to the first agent that arrives to the zone. The cause of this behavior is the `reward` method of the `InteractiveElement` class https://github.com/gaorkl/simple-playgrounds/blob/633adc7cf3fd382ab3b078a112d083f970a3152a/src/simple_playgrounds/element/element.py#L38 

I understand that the use of `self._reward_provided` is to avoid having variable rewards given to an agent during a step, since the engine is running 10 actual steps https://github.com/gaorkl/simple-playgrounds/blob/633adc7cf3fd382ab3b078a112d083f970a3152a/src/simple_playgrounds/common/definitions.py#L8 in each engine step.

For my project I created a custom `MultiAgentRewardZone` that gives reward on each step and I'm dealing with the variable rewards separately. However, I think it would be good to have the behavior adapted to work with multi-agent environments the same way as with single-agent ones. I.e only give a fixed amount of reward **to each agent** in each engine step (only in one of the actual steps).

 ----
PS: I'm mentioning @clement-moulin-frier and @eleninisioti so they can follow this issue

**Comment by gaorkl** [comment]
Hi!

You are perfectly right, this was put in place exactly for the reason you mentioned.

I didn't have this use case in the current main version so I didn't thought about it. 
But I will change it in the next release to generalize to multi agents.

Thank you very much for noticing that!

I will keep the issue open so that I remember it.

Cheers

Michael
